---
name: Build and upload

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-24.04
            shell: bash
            goarch: amd64

          - name: darwin
            os: macos-15
            shell: bash
            goarch: arm64

          - name: windows
            os: windows-2022
            shell: bash
            postfix: '.exe'
            goarch: amd64

    steps:
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install \
            libasound2-dev \
            libudev-dev \
            libx11-dev \
            libxrandr-dev \
            libgl-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxi-dev \
            libxxf86vm-dev \
            libenet-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install enet

      - name: Install packages (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ${{ matrix.packages }}

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
        with:
          fetch-depth: 0

      - name: Project Version
        id: project_version
        run: echo "project_version=$(git describe --always --tags --match '*.*' | sed 's/^v//')" >> "${GITHUB_OUTPUT}"

      - name: Setup Go version
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 #5.3.0
        with:
          go-version: '>=1.24.0'

      - name: Install go dependencies
        run: |
          go mod tidy

      - name: Build
        run: |
          mkdir out
          env \
            GOOS=${{ matrix.name }} \
            GOARCH=${{ matrix.goarch }} \
            go build -o \
            out/pvdn-${{ steps.project_version.outputs.project_version }}-${{ matrix.name }}${{ matrix.postfix }} \
            lgk/main.go

      - name: Upload build
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 #4.6.0
        with:
          name: pvdn-${{ steps.project_version.outputs.project_version }}-${{ matrix.name }}
          path: |
            out/pvdn-${{ steps.project_version.outputs.project_version }}-${{ matrix.name }}${{ matrix.postfix }}
          retention-days: 30
