---
name: Build and upload

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: ${{ matrix.config.shell }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux
            os: ubuntu-24.04
            shell: bash
            postfix: linux
            goos: linux
            goarch: amd64
          - name: macOS
            os: macos-15
            shell: bash
            postfix: darwin
            goos: darwin
            goarch: arm64
          - name: Windows
            os: ubuntu-24.04
            shell: bash
            postfix: windows.exe
            goos: windows
            goarch: amd64

    steps:
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install \
            libasound2-dev \
            libudev-dev \
            libx11-dev \
            libxrandr-dev \
            libgl-dev

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
        with:
          fetch-depth: 0

      - name: Project Version
        id: project_version
        run: echo "project_version=$(git describe --always --tags --match '*.*' | sed 's/^v//')" >> "${GITHUB_OUTPUT}"

      - name: Setup Go version
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 #5.3.0
        with:
          go-version: '>=1.24.0'

      - name: Install go dependencies
        run: |
          go mod tidy

      - name: Build
        run: |
          mkdir out
          env \
              GOOS=${{ matrix.config.goos }} \
              GOARCH=${{ matrix.config.goarch }} \
              go build -o \
              out/pvdn-${{ steps.project_version.outputs.project_version }}-${{ matrix.config.postfix }} \
              lgk/main.go

      - name: Upload build
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 #4.6.0
        with:
          name: pvdn-${{ steps.project_version.outputs.project_version }}-${{ matrix.config.postfix }}
          path: |
            out/pvdn-${{ steps.project_version.outputs.project_version }}-${{ matrix.config.postfix }}
          retention-days: 30
